---
title: 'Some Facts on Coronavirus'
subtitle: 
summary: This post aims to give some basic facts on coronavirus epidemic which took place in the last couple of months and spreaded around all the world. The main objective is to focus on the economic consequences.
authors:
- admin
tags:
- 
categories: []
date: "2020-03-07T00:00:00Z"
featured:
draft: true

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Placement options: 1 = Full column width, 2 = Out-set, 3 = Screen-width
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
header:
  caption: ''
  image: ''
  
image:
  placement: 2
  caption:
  focal_point: Top
  preview_only: false
---

This post aims to give some basic facts on coronavirus epidemic which took place in the last couple of months and spreaded around all the world. The main objective is to focus on the economic consequences.

```{r}
knitr::opts_chunk$set(message = FALSE, warning=FALSE, echo = TRUE, cache = FALSE)
```


```{r}
library(tidyverse)
library(lubridate)
theme_set(theme_light())
graphics.off()
```

```{r}
dat <- tibble(Date = today() + days(0:99),
              Vals = rnorm(100))

ggplot(dat, aes(Date, Vals))+
  geom_line(col = "black")+
  geom_hline(yintercept = 0, col = "red", linetype = "dashed")+
  geom_hline(yintercept = 1, col = "blue", linetype = "dashed")+
  geom_hline(yintercept = -1, col = "black", linetype = "dashed")
```

